# hodge_ring_check.py -- referee check (Theorem D, note_cm_sixfolds Sec. 7), written from scratch; does not
# import project code.  Model: H^*(A^k, C) = /\( X1(x)U1 + X1v(x)U1' + X2(x)U2 + X2v(x)U2' ), X_i = C^3,
# U = C^k (one copy index per embedding of L).  Hodge group (Prop. typeIV-hg) over C:
# G_H = {(g1,g2) in GL(X1) x GL(X2): det g1 det g2 = 1}.  Its invariants are
#     B = (+)_a  Inv_a(side 1) (x) Inv_a(side 2),
# Inv_a = SL3-invariants of det-weight a in the one-sided algebra /\(X(x)U) (x) /\(Xv(x)U').
# Generators of the candidate subring R: divisor classes theta_{cc'} = sum_i x_{i,c} y_{i,c'} (each side)
# and the C-span of the pull-backs f^*W(A,K), which is span{b1[J] b2[J']} + span{bb1[J] bb2[J']}
# (b[J] = "determinant" of three x's with copy indices J; bb[J] the same with y's).
#
# Part A (one-sided, k = 1..KMAX): for every dominant GL_k x GL_k weight (nu, nu') compute
#   h(nu,nu') = dim of {v of SL3-weight (a,a,a): killed by sl3 and gl_k x gl_k raising operators}
#   (= multiplicity of the irreducible GL_k x GL_k module of highest weight (nu,nu') in Inv_a), compare with
#   skew Howe duality: Inv_a = (+)_mu S_{(mu+a)'}(U) (x) S_{mu'}(U')  (a >= 0; mirror for a < 0),
#   and check that the subalgebra generated by the theta's and the b's (bb's) contains each highest weight
#   vector of Inv_a.  (Inv_a is multiplicity free, so this proves Inv_a = (algebra generated)_a in that k.)
# Part A' (k <= 3): brute-force dim Inv_a in every degree over ALL weights (sl3 kernels), vs Howe formula.
# Part B: dim B^j(A^k) and dim of the Lefschetz part from Part A, compared with the project's hodge_dims.out.
# Part C (k = 2, all weights, two-sided, no factorization): dim of G_H-invariants (kernel of the 4 sl3 raising
#   operators on SL3xSL3-weight (a,a,a|a,a,a)) and rank of the span of products of the actual generators
#   theta1, theta2, U+ = b1[J] b2[J'], U- = bb1[J] bb2[J'], degree by degree.
# Ranks mod P = 2^31-1.  Certification: rank_P(generated) <= dim_Q(generated) <= dim_Q(invariants)
#   <= dim of kernel mod P; equality of the two outer numbers proves equality over Q.
import os, sys, itertools, math, time, json
from collections import defaultdict
from functools import lru_cache
import flint

P = 2147483647

def popc(x): return bin(x).count('1')

class Side:
    """one-sided exterior algebra on x(i,c), y(i,c), i<3, c<k; bit offset 'off'"""
    def __init__(self, k, off=0):
        self.k, self.off = k, off
    def x(self, i, c): return self.off + 6*c + i
    def y(self, i, c): return self.off + 6*c + 3 + i

def mono_sign_merge(m1, m2):
    # sign of (wedge of m1 in increasing order) ^ (wedge of m2 in increasing order) -> increasing order
    s = 0; mm = m2
    while mm:
        low = mm & -mm; q = low.bit_length() - 1
        s += popc(m1 >> (q + 1))
        mm ^= low
    return -1 if (s & 1) else 1

def emul(A, B):
    R = defaultdict(int)
    for m1, c1 in A.items():
        for m2, c2 in B.items():
            if m1 & m2: continue
            R[m1 | m2] += mono_sign_merge(m1, m2) * c1 * c2
    return {m: c % P for m, c in R.items() if c % P}

def theta(S, c, cp):
    return {(1 << S.x(i, c)) | (1 << S.y(i, cp)): (mono_sign_merge(1 << S.x(i, c), 1 << S.y(i, cp))) % P for i in range(3)}

def bdet(S, J, which):
    E = defaultdict(int)
    for perm in itertools.permutations(range(3)):
        sg = 1
        for i in range(3):
            for j in range(i + 1, 3):
                if perm[i] > perm[j]: sg = -sg
        el = {0: 1}
        for t in range(3):
            v = S.x(perm[t], J[t]) if which == 'x' else S.y(perm[t], J[t])
            el = emul(el, {1 << v: 1})
        for m, c in el.items():
            E[m] += sg * c
    return {m: c % P for m, c in E.items() if c % P}

def apply_op(mono, op):
    """op: list of (src_bit, dst_bit, coef); even derivation. returns dict mono->coef"""
    out = defaultdict(int)
    for s, t, cf in op:
        if not (mono >> s) & 1: continue
        if (mono >> t) & 1: continue
        lo, hi = (s, t) if s < t else (t, s)
        between = mono & (((1 << hi) - 1) ^ ((1 << (lo + 1)) - 1))
        sg = -1 if popc(between) & 1 else 1
        out[(mono ^ (1 << s)) | (1 << t)] += sg * cf
    return out

def sl3_ops(S):
    k = S.k
    e01 = [(S.x(1, c), S.x(0, c), 1) for c in range(k)] + [(S.y(0, c), S.y(1, c), -1) for c in range(k)]
    e12 = [(S.x(2, c), S.x(1, c), 1) for c in range(k)] + [(S.y(1, c), S.y(2, c), -1) for c in range(k)]
    return [e01, e12]

def gl_ops(S):
    k = S.k
    ops = []
    for c in range(k - 1):
        ops.append([(S.x(i, c + 1), S.x(i, c), 1) for i in range(3)])
    for c in range(k - 1):
        ops.append([(S.y(i, c + 1), S.y(i, c), 1) for i in range(3)])
    return ops

def weight_monomials(S, nu, nup, a):
    """monomials with GL_k weights (nu, nu') and SL3 weight (a,a,a) (x counts minus y counts per i = a)"""
    k = S.k
    subsets = {n: [c for c in itertools.combinations(range(3), n)] for n in range(4)}
    res = []
    def rec(c, diff, mono):
        if c == k:
            if diff == (a, a, a): res.append(mono)
            return
        rem = k - c - 1
        for sx in subsets[nu[c]]:
            for ty in subsets[nup[c]]:
                nd = list(diff)
                m = mono
                for i in sx: nd[i] += 1; m |= 1 << S.x(i, c)
                for i in ty: nd[i] -= 1; m |= 1 << S.y(i, c)
                # prune: each remaining copy changes diff[i] by at most 1 in either direction
                if all(abs(nd[i] - a) <= rem for i in range(3)):
                    rec(c + 1, tuple(nd), m)
    rec(0, (0, 0, 0), 0)
    return sorted(res)

def kernel_dim(W, ops):
    """dim of common kernel of the ops on span(W) (mod P), iteratively"""
    n = len(W)
    if n == 0: return 0, None
    idx = {m: j for j, m in enumerate(W)}
    K = None   # nmod_mat n x r basis (columns)
    for op in ops:
        tgt = {}; entries = []
        for j, m in enumerate(W):
            for mm, cf in apply_op(m, op).items():
                if cf % P == 0: continue
                r = tgt.setdefault(mm, len(tgt))
                entries.append((r, j, cf % P))
        if not tgt: continue
        M = flint.nmod_mat(len(tgt), n, P)
        for r, j, cf in entries:
            M[r, j] = (int(M[r, j]) + cf) % P
        Prod = M if K is None else M * K
        X, nul = Prod.nullspace()
        if nul == 0: return 0, None
        # basis of nullspace: first nul columns of X
        N = flint.nmod_mat(Prod.ncols(), nul, P)
        for i in range(Prod.ncols()):
            for c in range(nul):
                N[i, c] = X[i, c]
        K = N if K is None else K * N
    return (n if K is None else K.ncols()), K

def conj(lam, length):
    return tuple(sum(1 for x in lam if x >= c) for c in range(1, length + 1))

def dim_schur(lam, k):
    """dim of GL_k irreducible with highest weight lam (partition, <= k parts), hook content formula"""
    lam = [x for x in lam if x > 0]
    if len(lam) > k: return 0
    num = 1; den = 1
    lamc = conj(lam, lam[0] if lam else 0)
    for i, r in enumerate(lam):
        for j in range(r):
            num *= (k + j - i)
            den *= (r - j - 1) + (lamc[j] - i - 1) + 1
    return num // den

def howe_constituents(k, a):
    """list of (nu, nu') highest weights in Inv_a"""
    out = []
    A = abs(a)
    for mu in itertools.product(range(k + 1), repeat=3):
        if not (mu[0] >= mu[1] >= mu[2]): continue
        if mu[0] + A > k: continue
        lam = tuple(x + A for x in mu)
        if a >= 0:
            out.append((conj(lam, k), conj(mu, k)))
        else:
            out.append((conj(mu, k), conj(lam, k)))
    return out

def dominant(k):
    return [nu for nu in itertools.product(range(3, -1, -1), repeat=k) if all(nu[i] >= nu[i+1] for i in range(k-1))]

def multisets3(k):
    return list(itertools.combinations_with_replacement(range(k), 3))

def contingency(rows, cols):
    """all nonneg integer matrices with given row and column sums (as tuples of tuples)"""
    k1, k2 = len(rows), len(cols)
    res = []
    def rec(i, colrem, acc):
        if i == k1:
            if all(c == 0 for c in colrem): res.append(tuple(acc))
            return
        # distribute rows[i] among columns with caps colrem
        def rec2(j, left, row):
            if j == k2 - 1:
                if left <= colrem[j]:
                    rec(i + 1, tuple(colrem[t] - (row + [left])[t] for t in range(k2)), acc + [tuple(row + [left])])
                return
            for v in range(min(left, colrem[j]) + 1):
                rec2(j + 1, left - v, row + [v])
        if k2 == 0:
            if rows[i] == 0: rec(i + 1, colrem, acc + [tuple()])
            return
        rec2(0, rows[i], [])
    rec(0, tuple(cols), [])
    return res

class ProdCache:
    def __init__(self, S):
        self.S = S; self.th = {}; self.cache = {(): {0: 1}}
    def theta(self, c, cp):
        if (c, cp) not in self.th: self.th[(c, cp)] = theta(self.S, c, cp)
        return self.th[(c, cp)]
    def theta_mono(self, N):
        factors = []
        for c, row in enumerate(N):
            for cp, v in enumerate(row):
                factors += [(c, cp)] * v
        key = tuple(factors)
        # longest cached prefix
        i = len(key)
        while key[:i] not in self.cache: i -= 1
        el = self.cache[key[:i]]
        for j in range(i, len(key)):
            el = emul(el, self.theta(*key[j]))
            self.cache[key[:j + 1]] = el
        return el

def onesided_products(S, PC, nu, nup, a, bcache):
    """generators products theta^N * b[J1]...b[Ja] (a>=0) or theta^N * bb[J1]...bb[J|a|] (a<0) of weight (nu,nu')"""
    k = S.k
    Ms = multisets3(k)
    def wt(J):
        w = [0]*k
        for c in J: w[c] += 1
        return w
    prods = []
    A = abs(a)
    for Js in itertools.combinations(Ms, A):
        beta = [0]*k
        for J in Js:
            for c, v in enumerate(wt(J)): beta[c] += v
        if a >= 0:
            rows = [nu[c] - beta[c] for c in range(k)]; cols = list(nup)
        else:
            rows = list(nu); cols = [nup[c] - beta[c] for c in range(k)]
        if min(rows) < 0 or min(cols) < 0 or sum(rows) != sum(cols): continue
        bel = {0: 1}
        for J in Js:
            key = (J, 'x' if a >= 0 else 'y')
            if key not in bcache: bcache[key] = bdet(S, J, key[1])
            bel = emul(bel, bcache[key])
        if not bel: continue
        for N in contingency(rows, cols):
            el = emul(PC.theta_mono(N), bel)
            if el: prods.append(el)
    return prods

def rank_of_columns(vecs, idx, n):
    if not vecs: return 0, None
    M = flint.nmod_mat(n, len(vecs), P)
    for j, v in enumerate(vecs):
        for m, cf in v.items():
            M[idx[m], j] = cf % P
    return M.rank(), M

def part_A(k, log):
    S = Side(k)
    ops_sl, ops_gl = sl3_ops(S), gl_ops(S)
    PC = ProdCache(S); bcache = {}
    doms = dominant(k)
    ok = True; nhw = 0; nchecked = 0
    t0 = time.time()
    for a in range(-k, k + 1):
        pred = set(howe_constituents(k, a))
        for nu in doms:
            for nup in doms:
                if sum(nu) - sum(nup) != 3 * a: continue
                W = weight_monomials(S, nu, nup, a)
                h, _ = kernel_dim(W, ops_sl + ops_gl) if W else (0, None)
                exp_h = 1 if (nu, nup) in pred else 0
                nchecked += 1
                if h != exp_h:
                    ok = False
                    log('   MISMATCH hw multiplicity k=%d a=%d nu=%s nu\'=%s: computed %d, Howe %d' % (k, a, nu, nup, h, exp_h))
                if exp_h == 1:
                    nhw += 1
                    idx = {m: j for j, m in enumerate(W)}
                    prods = onesided_products(S, PC, nu, nup, a, bcache)
                    # sanity: products are sl3-invariant
                    for v in prods[:50]:
                        for op in ops_sl:
                            img = defaultdict(int)
                            for m, cf in v.items():
                                for mm, c2 in apply_op(m, op).items():
                                    img[mm] = (img[mm] + cf * c2) % P
                            if any(x % P for x in img.values()):
                                ok = False; log('   NOT INVARIANT product at', nu, nup)
                                break
                    r1, G = rank_of_columns(prods, idx, len(W))
                    # images under gl raising ops
                    if r1 > 0:
                        imgs_rows = {}
                        entries = []
                        for j, v in enumerate(prods):
                            for oi, op in enumerate(ops_gl):
                                for m, cf in v.items():
                                    for mm, c2 in apply_op(m, op).items():
                                        r = imgs_rows.setdefault((oi, mm), len(imgs_rows))
                                        entries.append((r, j, cf * c2 % P))
                        if imgs_rows:
                            M2 = flint.nmod_mat(len(imgs_rows), len(prods), P)
                            for r, j, cf in entries:
                                M2[r, j] = (int(M2[r, j]) + cf) % P
                            r2 = M2.rank()
                        else:
                            r2 = 0
                        hwR = r1 - r2
                    else:
                        hwR = 0
                    if hwR != 1:
                        ok = False
                        log('   GENERATION FAILS k=%d a=%d nu=%s nu\'=%s: hw vectors in R = %d (products %d, rank %d)' % (k, a, nu, nup, hwR, len(prods), r1))
    log('Part A k=%d: dominant weight pairs checked %d, Howe constituents %d, all hw multiplicities as predicted and every hw vector in the generated algebra: %s  (%.1fs)' % (k, nchecked, nhw, ok, time.time() - t0))
    return ok

def howe_inv_dims(k):
    """dims[a][deg] of Inv_a from skew Howe duality (hook content formula)"""
    dims = defaultdict(lambda: defaultdict(int))
    for a in range(-k, k + 1):
        for (nu, nup) in howe_constituents(k, a):
            lam = conj(nu, 3) if False else None
            # nu, nu' are GL_k highest weights (entries <= 3); dimension = dim S_nu(C^k) * dim S_nu'(C^k)
            d1 = dim_schur([x for x in nu], k); d2 = dim_schur([x for x in nup], k)
            dims[a][sum(nu) + sum(nup)] += d1 * d2
    return dims

def part_A_brute(k, log):
    """all weights, kernel of sl3 raising ops -> dim Inv_a per degree"""
    S = Side(k); ops_sl = sl3_ops(S)
    dims = defaultdict(lambda: defaultdict(int))
    t0 = time.time()
    allw = list(itertools.product(range(4), repeat=k))
    for a in range(-k, k + 1):
        for nu in allw:
            for nup in allw:
                if sum(nu) - sum(nup) != 3 * a: continue
                W = weight_monomials(S, nu, nup, a)
                if not W: continue
                h, _ = kernel_dim(W, ops_sl)
                dims[a][sum(nu) + sum(nup)] += h
    hd = howe_inv_dims(k)
    ok = all(dims[a][j] == hd[a][j] for a in range(-k, k + 1) for j in range(0, 6 * k + 1))
    log('Part A\' k=%d: brute-force dim Inv_a[deg] over all weights == Howe formula: %s  (%.1fs)' % (k, ok, time.time() - t0))
    for a in range(0, k + 1):
        log('   a=%d: %s' % (a, [dims[a][j] for j in range(0, 6 * k + 1)]))
    return ok, dims

def part_B(k, inv):
    """dim B^j(A^k), j = codim 0..6k, and Lefschetz part"""
    Bd, Dd = [], []
    for j in range(0, 6 * k + 1):
        tot = 0; lef = 0
        for a in range(-k, k + 1):
            s = sum(inv[a][j1] * inv[a][2 * j - j1] for j1 in range(0, 2 * j + 1))
            tot += s
            if a == 0: lef += s
        Bd.append(tot); Dd.append(lef)
    return Bd, Dd

def parse_hodge_dims(path):
    res = {}
    cur = None
    for line in open(path, encoding='utf-8'):
        line = line.strip()
        if line.startswith('n ='):
            cur = int(line.split()[2]); res[cur] = {}
        elif line.startswith('(') and cur is not None:
            t = eval(line)
            res[cur][t[0]] = (t[1], t[2])
    return res

def part_C(k, log):
    """two-sided direct computation for A^k (intended for k <= 2), all GL_k^4 weights"""
    S1, S2 = Side(k, 0), Side(k, 6 * k)
    ops = sl3_ops(S1) + sl3_ops(S2)
    allw = list(itertools.product(range(4), repeat=k))
    PC1, PC2 = ProdCache(S1), ProdCache(S2)
    Ms = multisets3(k)
    bc = {}
    def b(S, J, w):
        key = (S.off, J, w)
        if key not in bc: bc[key] = bdet(S, J, w)
        return bc[key]
    Bdeg = defaultdict(int); Rdeg = defaultdict(int)
    t0 = time.time()
    side_w = defaultdict(list)       # a -> list of (nu, nu', monomials)
    for a in range(-k, k + 1):
        for nu in allw:
            for nup in allw:
                if sum(nu) - sum(nup) != 3 * a: continue
                Wm = weight_monomials(S1, nu, nup, a)
                if Wm: side_w[a].append((nu, nup))
    for a in range(-k, k + 1):
        for (nu1, nup1) in side_w[a]:
            W1 = weight_monomials(S1, nu1, nup1, a)
            for (nu2, nup2) in side_w[a]:
                W2 = weight_monomials(S2, nu2, nup2, a)
                W = sorted(m1 | m2 for m1 in W1 for m2 in W2)
                deg = (sum(nu1) + sum(nup1) + sum(nu2) + sum(nup2))
                assert deg % 2 == 0
                h, _ = kernel_dim(W, ops)
                Bdeg[deg // 2] += h
                if h == 0: continue
                # products of generators theta1^N1 theta2^N2 (U+)^p (U-)^q, p - q = a
                prods = []
                for q in range(0, k + 1):
                    p = a + q
                    if p < 0: continue
                    for Jp1 in itertools.combinations(Ms, p):
                        for Jq1 in itertools.combinations(Ms, q):
                            bx = [0]*k; by = [0]*k
                            for J in Jp1:
                                for c in J: bx[c] += 1
                            for J in Jq1:
                                for c in J: by[c] += 1
                            rows1 = [nu1[c] - bx[c] for c in range(k)]; cols1 = [nup1[c] - by[c] for c in range(k)]
                            if min(rows1) < 0 or min(cols1) < 0 or sum(rows1) != sum(cols1): continue
                            for Jp2 in itertools.combinations(Ms, p):
                                for Jq2 in itertools.combinations(Ms, q):
                                    bx2 = [0]*k; by2 = [0]*k
                                    for J in Jp2:
                                        for c in J: bx2[c] += 1
                                    for J in Jq2:
                                        for c in J: by2[c] += 1
                                    rows2 = [nu2[c] - bx2[c] for c in range(k)]; cols2 = [nup2[c] - by2[c] for c in range(k)]
                                    if min(rows2) < 0 or min(cols2) < 0 or sum(rows2) != sum(cols2): continue
                                    # U+ = b1[J] b2[J'] paired in the listed order, U- = bb1 bb2
                                    U = {0: 1}
                                    for J1, J2 in zip(Jp1, Jp2):
                                        U = emul(U, emul(b(S1, J1, 'x'), b(S2, J2, 'x')))
                                    for J1, J2 in zip(Jq1, Jq2):
                                        U = emul(U, emul(b(S1, J1, 'y'), b(S2, J2, 'y')))
                                    if not U: continue
                                    for N1 in contingency(rows1, cols1):
                                        T1 = emul(PC1.theta_mono(N1), U)
                                        if not T1: continue
                                        for N2 in contingency(rows2, cols2):
                                            el = emul(PC2.theta_mono(N2), T1)
                                            if el: prods.append(el)
                idx = {m: j for j, m in enumerate(W)}
                r, _ = rank_of_columns(prods, idx, len(W))
                Rdeg[deg // 2] += r
    log('Part C k=%d (two-sided, all weights): %.1fs' % (k, time.time() - t0))
    return Bdeg, Rdeg

if __name__ == '__main__':
    KMAX = int(sys.argv[1]) if len(sys.argv) > 1 else 3
    out = open(sys.argv[2], 'w', encoding='utf-8') if len(sys.argv) > 2 else sys.stdout
    def log(*a):
        print(*a, file=out, flush=True)
    log('hodge_ring_check.py KMAX=%d  P=%d' % (KMAX, P))
    allok = True
    hd = parse_hodge_dims(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'hodge_dims.out'))
    for k in range(1, KMAX + 1):
        okA = part_A(k, log)
        allok &= okA
        if k <= 3:
            okAb, _ = part_A_brute(k, log)
            allok &= okAb
        inv = howe_inv_dims(k)
        Bd, Dd = part_B(k, inv)
        log('Part B k=%d: dim B^j(A^k), j=0..%d: %s' % (k, 6 * k, Bd))
        log('            Lefschetz part D^j:        %s' % Dd)
        if k in hd:
            cmp_ = all(hd[k][j] == (Bd[j], Dd[j]) for j in range(0, 6 * k + 1))
            log('            equal to project hodge_dims.out (Weyl character formula): %s' % cmp_)
            allok &= cmp_
    if KMAX >= 2:
        for k in (1, 2):
            Bdeg, Rdeg = part_C(k, log)
            inv = howe_inv_dims(k); Bd, Dd = part_B(k, inv)
            okC = all(Bdeg[j] == Bd[j] and Rdeg[j] == Bd[j] for j in range(0, 6 * k + 1))
            log('Part C k=%d: invariants per codim  %s' % (k, [Bdeg[j] for j in range(0, 6 * k + 1)]))
            log('            generated per codim   %s' % ([Rdeg[j] for j in range(0, 6 * k + 1)]))
            log('            invariants == Part B and generated == invariants: %s' % okC)
            allok &= okC
    log('ALL OK' if allok else 'SOME CHECK FAILED')
