# periods_check.py -- referee check for Theorem D (note_cm_sixfolds, Sec. 7), written from scratch
# (does not import any project code).
#
# For several (d, m), random L-hermitian H and random points of the period domain
# U(H_1)/(U(p1) x U(q1)) x U(H_2)/(U(p2) x U(q2)) we build the complex structure J on V_R = (L^3) (x) R
# in an explicit Q-basis of V = L^3 (L = Q(sqrt(-d), sqrt(m))), with Riemann form
# psi = Tr_{L/Q}(sqrt(-d) H), and check:
#   (i)   psi(x, Jy) symmetric positive definite, J commutes with L, Hodge multiplicities
#         n_sigma = dim(V_sigma cap {J = i}) are (2,1,1,2) at (s1, s1bar, s2, s2bar);
#         K-multiplicities (3,3), K'-multiplicities (4,2);
#         H has signature (2,1) at the place under sigma1 and (1,2) at the other (convention psi(x,Jx) > 0);
#   (ii)  Lemma lem:typeIV-det exactly (sympy) for a = 1, a = a0, a random a;
#         a0 = -sqrt(m) det_L H totally positive, psi_a0(x, Jx) > 0, det h_a0 = -(square) exactly,
#         signature of h_a0 = (3,3); the same a0 is obtained with the opposite positivity convention;
#   (F)   Hodge circle h(t) = cos t + sin t J: det of h(t) on V_sigma for each embedding sigma of L
#         (numerically from the 12x12 matrices), det_K h(t) = 1, det_L h(t) at the two places = e^{+-it};
#         exact Lie algebras: dim Lie(U_L(H)) = 18, dim Lie(G_H) = 17 (tr_K = 0),
#         dim Lie(R_{F/Q} SU(H)) = 16 (tr_L = 0); J in Lie(G_H), J not in Lie(R SU(H));
#         the ideal of Lie(U_L(H)) (x) C generated by J has dimension 17 and equals Lie(G_H) (x) C;
#         its commutant in End(V_C) has dimension 4 (= L (x) C).
import sys, random, math, itertools
from fractions import Fraction as Fr
import numpy as np
import sympy as sp
import flint

def lmul(a, b, d, m):
    a0, a1, a2, a3 = a; b0, b1, b2, b3 = b
    return (a0*b0 + m*a1*b1 - d*a2*b2 - d*m*a3*b3,
            a0*b1 + a1*b0 - d*(a2*b3 + a3*b2),
            a0*b2 + a2*b0 + m*(a1*b3 + a3*b1),
            a0*b3 + a3*b0 + a1*b2 + a2*b1)
def lconj(a): return (a[0], a[1], -a[2], -a[3])
def ladd(a, b): return tuple(x + y for x, y in zip(a, b))
def lsc(c, a): return tuple(c*x for x in a)
ZERO = (Fr(0),)*4; ONE = (Fr(1), Fr(0), Fr(0), Fr(0))
S = (Fr(0), Fr(1), Fr(0), Fr(0)); W = (Fr(0), Fr(0), Fr(1), Fr(0)); SW = (Fr(0), Fr(0), Fr(0), Fr(1))
BASIS = [ONE, S, W, SW]

def emb(a, d, m, sgn_s, sgn_w):
    # sgn_s = +1/-1: sqrt(m) -> sgn_s*sqrt(m); sgn_w: sqrt(-d) -> sgn_w * i sqrt(d)
    rs, rw = sgn_s*math.sqrt(m), sgn_w*1j*math.sqrt(d)
    return float(a[0]) + float(a[1])*rs + float(a[2])*rw + float(a[3])*rs*rw
EMBS = {'s1': (1, 1), 's1b': (1, -1), 's2': (-1, 1), 's2b': (-1, -1)}

def ldet3(H, d, m):
    def M(a, b): return lmul(a, b, d, m)
    t = ZERO
    for p in itertools.permutations(range(3)):
        sg = 1
        for i in range(3):
            for j in range(i+1, 3):
                if p[i] > p[j]: sg = -sg
        pr = M(M(H[0][p[0]], H[1][p[1]]), H[2][p[2]])
        t = ladd(t, lsc(sg, pr))
    return t

def random_H(d, m, rng):
    # random hermitian H with signature (2,1) at s -> +sqrt m and (1,2) at s -> -sqrt m
    while True:
        H = [[None]*3 for _ in range(3)]
        for r in range(3):
            H[r][r] = (Fr(rng.randint(-6, 6)), Fr(rng.randint(-4, 4)), Fr(0), Fr(0))
            for s_ in range(r+1, 3):
                x = tuple(Fr(rng.randint(-3, 3)) for _ in range(4))
                H[r][s_] = x; H[s_][r] = lconj(x)
        sig = []
        for e in ('s1', 's2'):
            Hc = np.array([[emb(H[r][c], d, m, *EMBS[e]) for c in range(3)] for r in range(3)])
            ev = np.linalg.eigvalsh(Hc)
            if np.min(np.abs(ev)) < 1e-6: break
            sig.append((int((ev > 0).sum()), int((ev < 0).sum())))
        if sig == [(2, 1), (1, 2)]:
            return H

def matmul_L(ell, d, m):
    # 12x12 rational matrix of multiplication by ell on V = L^3, coordinates x[4r+j], basis BASIS[j]
    Mt = [[Fr(0)]*12 for _ in range(12)]
    for r in range(3):
        for j in range(4):
            img = lmul(ell, BASIS[j], d, m)
            for k in range(4):
                Mt[4*r+k][4*r+j] = img[k]
    return Mt

def psi_gram(H, d, m):
    G = [[Fr(0)]*12 for _ in range(12)]
    for r in range(3):
        for j in range(4):
            for s_ in range(3):
                for k in range(4):
                    v = lmul(lmul(W, BASIS[j], d, m), lmul(H[r][s_], lconj(BASIS[k]), d, m), d, m)
                    G[4*r+j][4*s_+k] = 4*v[0]           # Tr_{L/Q}
    return G

def tofl(Mt): return np.array([[float(x) for x in row] for row in Mt])

def real_of_complex(A):
    return np.block([[A.real, -A.imag], [A.imag, A.real]])

def expm(X):
    # scaling and squaring with Taylor (small matrices)
    nrm = np.linalg.norm(X); k = max(0, int(math.ceil(math.log2(nrm + 1e-30))) + 2)
    Y = X / (2**k); E = np.eye(X.shape[0], dtype=complex); T = np.eye(X.shape[0], dtype=complex)
    for n in range(1, 30):
        T = T @ Y / n; E = E + T
    for _ in range(k): E = E @ E
    return E

def hermitian_K_gram(H, a, d, m):
    # Gram matrix of h_a = Tr_{L/K}(a H) in the K-basis {e_r, s e_r}; entries returned as sympy numbers
    w = sp.sqrt(-sp.Integer(d))
    vecs = [(r, ONE) for r in range(3)] + [(r, S) for r in range(3)]
    G = sp.zeros(6, 6)
    for i, (r, u) in enumerate(vecs):
        for j, (s_, v) in enumerate(vecs):
            val = lmul(lmul(a, u, d, m), lmul(H[r][s_], lconj(v), d, m), d, m)
            # Tr_{L/K}(x) = 2 x0 + 2 x2 w
            G[i, j] = 2*sp.Rational(val[0].numerator, val[0].denominator) + \
                      2*sp.Rational(val[2].numerator, val[2].denominator)*w
    return G

def NF(a, m):  # norm F/Q of a = a0 + a1 s (a2 = a3 = 0)
    assert a[2] == 0 and a[3] == 0
    return a[0]*a[0] - m*a[1]*a[1]

def is_rat_square(q):
    q = Fr(q)
    if q < 0: return False
    n, dd = q.numerator, q.denominator
    return math.isqrt(n)**2 == n and math.isqrt(dd)**2 == dd

def fmpq_nullspace(rows, ncols):
    # exact null space from the reduced row echelon form (python-flint has rref but no nullspace)
    M = flint.fmpq_mat(len(rows), ncols, [x for row in rows for x in row])
    R, rk = M.rref()
    piv = []
    for i in range(rk):
        for j in range(ncols):
            if R[i, j] != 0:
                piv.append(j); break
    free = [j for j in range(ncols) if j not in set(piv)]
    basis = []
    for f in free:
        v = [flint.fmpq(0)]*ncols
        v[f] = flint.fmpq(1)
        for i, p in enumerate(piv):
            v[p] = -R[i, f]
        basis.append(v)
    return basis

def run_case(d, m, rng, nprng, log):
    H = random_H(d, m, rng)
    Ms, Mw = matmul_L(S, d, m), matmul_L(W, d, m)
    Psi = psi_gram(H, d, m)
    # exactness checks of psi: alternating, L-compatible (psi(l x, y) = psi(x, conj(l) y))
    PsiQ = sp.Matrix(12, 12, lambda i, j: sp.Rational(Psi[i][j].numerator, Psi[i][j].denominator))
    MsQ = sp.Matrix(12, 12, lambda i, j: sp.Rational(Ms[i][j].numerator, Ms[i][j].denominator))
    MwQ = sp.Matrix(12, 12, lambda i, j: sp.Rational(Mw[i][j].numerator, Mw[i][j].denominator))
    ok_alt = (PsiQ.T == -PsiQ)
    ok_compat = (MsQ.T*PsiQ == PsiQ*MsQ) and (MwQ.T*PsiQ == -PsiQ*MwQ)
    # complex coordinates: z_i = sigma_i(x_r), places i = 1 (s1), 2 (s2)
    Tc = np.zeros((6, 12), dtype=complex)
    for pi, e in enumerate(('s1', 's2')):
        for r in range(3):
            for j in range(4):
                Tc[3*pi + r, 4*r + j] = emb(BASIS[j], d, m, *EMBS[e])
    T = np.vstack([Tc.real, Tc.imag]); Tinv = np.linalg.inv(T)
    Jblocks = []; sigs = []
    for pi, e in enumerate(('s1', 's2')):
        Hc = np.array([[emb(H[r][c], d, m, *EMBS[e]) for c in range(3)] for r in range(3)])
        # sigma_i(H(x,y)) = z^T H_i conj(z') = z'^* ... ; as a standard hermitian form z -> z^* A z
        # the matrix is A_i = H_i^T (= conj(H_i)); same eigenvalues as H_i
        Ai = Hc.T
        ev, U = np.linalg.eigh(Ai)
        sigs.append((int((ev > 0).sum()), int((ev < 0).sum())))
        Sk = nprng.normal(size=(3, 3)) + 1j*nprng.normal(size=(3, 3)); Sk = Sk - Sk.conj().T
        g = expm(np.linalg.solve(Ai, Sk) * 0.7)
        assert np.allclose(g.conj().T @ Ai @ g, Ai, atol=1e-8)
        Q = g @ U                                  # columns: H-orthogonal, signs of ev
        D = np.diag([1j if x > 0 else -1j for x in ev])
        Jblocks.append(Q @ D @ np.linalg.inv(Q))
    Jc = np.zeros((6, 6), dtype=complex); Jc[:3, :3] = Jblocks[0]; Jc[3:, 3:] = Jblocks[1]
    J = Tinv @ real_of_complex(Jc) @ T
    Psif, Msf, Mwf = tofl(Psi), tofl(Ms), tofl(Mw)
    res = {}
    res['J2=-1'] = np.allclose(J @ J, -np.eye(12), atol=1e-8)
    res['J commutes with L'] = np.allclose(J @ Msf, Msf @ J, atol=1e-8) and np.allclose(J @ Mwf, Mwf @ J, atol=1e-8)
    Sym = Psif @ J
    res['psi(x,Jy) symmetric'] = np.allclose(Sym, Sym.T, atol=1e-7)
    res['psi(x,Jx)>0'] = bool(np.linalg.eigvalsh((Sym + Sym.T)/2).min() > 0)
    res['psi(Jx,Jy)=psi'] = np.allclose(J.T @ Psif @ J, Psif, atol=1e-7)
    # multiplicities
    nmult = {}
    Jcx = J.astype(complex)
    for e, (ss, sw) in EMBS.items():
        A = np.vstack([Msf - ss*math.sqrt(m)*np.eye(12), Mwf - sw*1j*math.sqrt(d)*np.eye(12)])
        u, sv, vh = np.linalg.svd(A)
        Bs = vh[-3:].conj().T                      # 12x3 basis of V_sigma (null space)
        assert sv[-3:].max() < 1e-8 and sv[-4] > 1e-6
        C = np.linalg.lstsq(Bs, Jcx @ Bs, rcond=None)[0]
        evc = np.linalg.eigvals(C)
        nmult[e] = int(sum(1 for z in evc if abs(z - 1j) < 1e-6))
        # Hodge circle determinant on V_sigma at t = 0.37
        t = 0.37
        Ct = np.linalg.lstsq(Bs, (math.cos(t)*np.eye(12) + math.sin(t)*Jcx) @ Bs, rcond=None)[0]
        res['det_h(t) on V_' + e] = complex(np.round(np.linalg.det(Ct), 10))
        res['expected e^{it(n_s - n_sbar)} on V_' + e] = None
    for e, eb in (('s1', 's1b'), ('s1b', 's1'), ('s2', 's2b'), ('s2b', 's2')):
        t = 0.37
        exp_ = np.exp(1j*t*(nmult[e] - nmult[eb]))
        res['expected e^{it(n_s - n_sbar)} on V_' + e] = complex(np.round(exp_, 10))
    res['n_sigma (s1,s1b,s2,s2b)'] = (nmult['s1'], nmult['s1b'], nmult['s2'], nmult['s2b'])
    res['K-mult (tau, taubar)'] = (nmult['s1'] + nmult['s2'], nmult['s1b'] + nmult['s2b'])
    res["K'-mult"] = (nmult['s1'] + nmult['s2b'], nmult['s1b'] + nmult['s2'])
    res['H signature at (s1-place, s2-place)'] = tuple(sigs)
    t = 0.37
    res['det_K h(t) (= det on V_s1 + V_s2)'] = complex(np.round(res['det_h(t) on V_s1']*res['det_h(t) on V_s2'], 10))
    # ---------- (ii): a0 and Lemma
    DeltaL = ldet3(H, d, m)
    assert DeltaL[2] == 0 and DeltaL[3] == 0, 'det_L H not in F?'
    a0 = lsc(-1, lmul(S, DeltaL, d, m))
    a0v = [float(a0[0]) + float(a0[1])*math.sqrt(m), float(a0[0]) - float(a0[1])*math.sqrt(m)]
    res['a0 in F'] = (a0[2] == 0 and a0[3] == 0)
    res['a0 totally positive'] = (a0v[0] > 0 and a0v[1] > 0)
    Ma0 = tofl(matmul_L(a0, d, m))
    Sym0 = Ma0.T @ Psif @ J                         # psi_a0(x, Jy) = psi(a0 x, J y)
    res['psi_a0(x,Jx)>0'] = bool(np.allclose(Sym0, Sym0.T, atol=1e-6) and np.linalg.eigvalsh((Sym0+Sym0.T)/2).min() > 0)
    arand = (Fr(rng.randint(1, 9)), Fr(rng.randint(-3, 3)), Fr(0), Fr(0))
    lemma_ok = True; dets = {}
    for name, a in (('1', ONE), ('a0', a0), ('arand', arand)):
        G = hermitian_K_gram(H, a, d, m)
        dt = sp.nsimplify(sp.expand(G.det()))
        dt = sp.Rational(dt)
        pred = Fr(NF(a, m))**3 * Fr(NF(DeltaL, m)) * Fr(4*m)**3
        dets[name] = dt
        lemma_ok &= (Fr(int(dt.p), int(dt.q)) == pred)
        if name == 'a0':
            Gc = np.array(G.subs(sp.sqrt(-sp.Integer(d)), sp.I*sp.sqrt(d)).evalf(), dtype=complex)
            evh = np.linalg.eigvalsh((Gc + Gc.conj().T)/2)
            res['signature h_a0'] = (int((evh > 0).sum()), int((evh < 0).sum()))
            res['h_a0 hermitian'] = bool(np.allclose(Gc, Gc.conj().T))
    res['Lemma det formula exact (a=1,a0,arand)'] = lemma_ok
    res['-det h_a0 is a rational square'] = is_rat_square(-Fr(int(dets['a0'].p), int(dets['a0'].q)))
    res['det h_a0 = -(8 m^3 N(Delta)^2)^2'] = (Fr(int(dets['a0'].p), int(dets['a0'].q)) == -(8*m**3*Fr(NF(DeltaL, m))**2)**2)
    # opposite convention: psi' = -psi, H' = -H; sqrt(m)' := the root positive where H' has signature (2,1)
    # (that is the s2-place), i.e. sqrt(m)' = -s; a0' = -sqrt(m)' det_L H' = -(-s)(-Delta) = a0
    a0p = lsc(-1, lmul(lsc(-1, S), lsc(-1, DeltaL), d, m))
    res["a0 (opposite convention) == a0"] = (a0p == a0)
    res['psi exact: alternating & L-compatible'] = bool(ok_alt and ok_compat)
    return H, J, Ms, Mw, Psi, res

def lie_checks(H, J, Ms, Mw, Psi, d, m, log):
    out = {}
    # exact basis of Lie(U_L(H)) = {X : X Ms = Ms X, X Mw = Mw X, X^T Psi + Psi X = 0}
    rows = []
    def idx(i, j): return 12*i + j
    for (A,) in ((Ms,), (Mw,)):
        for i in range(12):
            for j in range(12):
                row = [flint.fmpq(0)]*144
                # (X A - A X)[i,j] = sum_k X[i,k] A[k,j] - A[i,k] X[k,j]
                for k in range(12):
                    if A[k][j] != 0: row[idx(i, k)] += flint.fmpq(A[k][j].numerator, A[k][j].denominator)
                    if A[i][k] != 0: row[idx(k, j)] -= flint.fmpq(A[i][k].numerator, A[i][k].denominator)
                rows.append(row)
    for i in range(12):
        for j in range(12):
            row = [flint.fmpq(0)]*144
            # (X^T Psi + Psi X)[i,j] = sum_k X[k,i] Psi[k,j] + Psi[i,k] X[k,j]
            for k in range(12):
                if Psi[k][j] != 0: row[idx(k, i)] += flint.fmpq(Psi[k][j].numerator, Psi[k][j].denominator)
                if Psi[i][k] != 0: row[idx(k, j)] += flint.fmpq(Psi[i][k].numerator, Psi[i][k].denominator)
            rows.append(row)
    B = fmpq_nullspace(rows, 144)
    out['dim Lie(U_L(H))'] = len(B)
    Bm = [np.array([[float(int(v[12*i+j].p))/float(int(v[12*i+j].q)) for j in range(12)] for i in range(12)]) for v in B]
    Bq = [[[v[12*i+j] for j in range(12)] for i in range(12)] for v in B]
    def trq(Mq, A):  # tr(M_A X) exactly for X in basis, A rational 12x12 (list) or None
        return None
    # linear functionals: tr(X), tr(Mw X), tr(Ms X), tr(Msw X)
    Msw = [[sum((Ms[i][k]*Mw[k][j] for k in range(12)), Fr(0)) for j in range(12)] for i in range(12)]
    def functional(A):
        vals = []
        for X in Bq:
            t = flint.fmpq(0)
            for i in range(12):
                for k in range(12):
                    a = A[i][k] if A is not None else (Fr(1) if i == k else Fr(0))
                    if a != 0: t += flint.fmpq(a.numerator, a.denominator) * X[k][i]
            vals.append(t)
        return vals
    fI, fW, fS, fSW = functional(None), functional(Mw), functional(Ms), functional(Msw)
    def rank_of(funcs):
        M = flint.fmpq_mat(len(funcs), len(B), [x for f in funcs for x in f])
        return M.rank()
    out['dim Lie(G_H) (tr_K = 0)'] = len(B) - rank_of([fI, fW])
    out['dim Lie(R_{F/Q}SU(H)) (tr_L = 0)'] = len(B) - rank_of([fI, fW, fS, fSW])
    # J in Lie(U_L(H))? (least squares residual) and its traces
    Bmat = np.array([b.ravel() for b in Bm]).T
    coef, resid, rk, sv = np.linalg.lstsq(Bmat, J.ravel(), rcond=None)
    out['J in Lie(U_L(H)) (residual)'] = float(np.linalg.norm(Bmat @ coef - J.ravel()))
    Mwf, Msf, Mswf = tofl(Mw), tofl(Ms), tofl(Msw)
    out['tr J, tr Mw J (tr_K J = 0 iff both 0)'] = (round(float(np.trace(J)), 9), round(float(np.trace(Mwf @ J)), 9))
    out['tr Ms J, tr Msw J (tr_L J = 0 iff all four 0)'] = (round(float(np.trace(Msf @ J)), 9), round(float(np.trace(Mswf @ J)), 9))
    out['expected tr Msw J = -4 sqrt(md) * (n_s1 - n_s1b)'] = round(-4*math.sqrt(m*d), 9)
    # ideal generated by J in Lie(U_L(H)) (x) C
    def orth(vs, tol=1e-9):
        if not vs: return []
        A = np.array(vs).T
        u, s, vh = np.linalg.svd(A, full_matrices=False)
        r = int((s > tol*max(1.0, s[0])).sum())
        return [u[:, i] for i in range(r)]
    cur = orth([J.ravel().astype(complex)])
    while True:
        new = list(cur)
        for b in Bm:
            for v in cur:
                X = v.reshape(12, 12)
                new.append((b @ X - X @ b).ravel())
        nxt = orth(new)
        if len(nxt) == len(cur): break
        cur = nxt
    out['dim ideal generated by J'] = len(cur)
    # is the ideal inside Lie(G_H)? check tr X = tr Mw X = 0 for all X in ideal
    tk = max(max(abs(np.trace(v.reshape(12, 12))), abs(np.trace(Mwf @ v.reshape(12, 12)))) for v in cur)
    out['max |tr_K| on ideal'] = float(tk)
    # commutant of the ideal in End(V_C)
    rows = []
    for v in cur:
        X = v.reshape(12, 12)
        # [Y, X] = 0 linear in Y (vec row-major): (Y X - X Y)
        rows.append(np.kron(np.eye(12), X.T) - np.kron(X, np.eye(12)))
    A = np.vstack(rows)
    s = np.linalg.svd(A, compute_uv=False)
    out['dim commutant of ideal'] = int((s < 1e-8*s[0]).sum())
    return out

if __name__ == '__main__':
    seed = int(sys.argv[1]) if len(sys.argv) > 1 else 20261006
    rng = random.Random(seed); nprng = np.random.default_rng(seed)
    pairs = [(1, 2), (3, 5), (2, 3), (7, 5), (5, 6), (11, 13), (1, 5), (3, 2), (6, 7), (15, 11)]
    allok = True
    summary = []
    for (d, m) in pairs:
        for rep in range(2):
            H, J, Ms, Mw, Psi, res = run_case(d, m, rng, nprng, None)
            print('=== d=%d m=%d rep=%d' % (d, m, rep))
            for k, v in res.items():
                print('   %-48s %s' % (k, v))
            ok = (res['J2=-1'] and res['J commutes with L'] and res['psi(x,Jy) symmetric'] and res['psi(x,Jx)>0']
                  and res['psi(Jx,Jy)=psi'] and res['n_sigma (s1,s1b,s2,s2b)'] == (2, 1, 1, 2)
                  and res['K-mult (tau, taubar)'] == (3, 3) and res["K'-mult"] == (4, 2)
                  and res['H signature at (s1-place, s2-place)'] == ((2, 1), (1, 2))
                  and res['a0 in F'] and res['a0 totally positive'] and res['psi_a0(x,Jx)>0']
                  and res['Lemma det formula exact (a=1,a0,arand)'] and res['-det h_a0 is a rational square']
                  and res['det h_a0 = -(8 m^3 N(Delta)^2)^2'] and res['signature h_a0'] == (3, 3)
                  and res['a0 (opposite convention) == a0'] and res['psi exact: alternating & L-compatible']
                  and abs(res['det_K h(t) (= det on V_s1 + V_s2)'] - 1) < 1e-8
                  and all(abs(res['det_h(t) on V_' + e] - res['expected e^{it(n_s - n_sbar)} on V_' + e]) < 1e-8 for e in EMBS)
                  and abs(res['det_h(t) on V_s1'] - 1) > 0.1 and abs(res['det_h(t) on V_s2'] - 1) > 0.1)
            if rep == 0:
                lc = lie_checks(H, J, Ms, Mw, Psi, d, m, None)
                for k, v in lc.items():
                    print('   %-48s %s' % (k, v))
                ok = ok and lc['dim Lie(U_L(H))'] == 18 and lc['dim Lie(G_H) (tr_K = 0)'] == 17 \
                    and lc['dim Lie(R_{F/Q}SU(H)) (tr_L = 0)'] == 16 and lc['J in Lie(U_L(H)) (residual)'] < 1e-8 \
                    and lc['dim ideal generated by J'] == 17 and lc['max |tr_K| on ideal'] < 1e-8 \
                    and lc['dim commutant of ideal'] == 4 \
                    and abs(lc['tr Ms J, tr Msw J (tr_L J = 0 iff all four 0)'][1] - lc['expected tr Msw J = -4 sqrt(md) * (n_s1 - n_s1b)']) < 1e-6
            print('   CASE OK' if ok else '   CASE FAIL')
            allok &= ok
            summary.append(((d, m, rep), ok))
    print('SUMMARY: %d cases, all ok = %s' % (len(summary), allok))
