# hodge_ring_gen.py -- check: for the very general member A, is the Hodge ring
# of A^n generated by divisor classes and the pullbacks f^* W(A,K) (f in Hom(A^n, A) (x) Q = L^n)?
#
# Model over C (cohomology = exterior algebra on V^n (x) C, dual coordinates):
#   x(a,j): sigma1-part, xb(a,j): conj(sigma1)-part, y(a,j): sigma2-part, yb(a,j): conj(sigma2)-part,
#   a = 1..3 (L-coordinate), j = 1..n (factor of A^n).  Lef_C = GL3 x GL3, Hg_C = {det g1 det g2 = 1}.
#   Divisor classes (D^1 (x) C, = Lef-invariants of degree 2):  w1[j,k] = sum_a x(a,j) xb(a,k),
#      w2[j,k] = sum_a y(a,j) yb(a,k)   (2 n^2 classes; = dim NS(A^n)_Q, checked against hodge_dims.py).
#   Weil-type generators U: b1[J] b2[J'] and bb1[J] bb2[J'], J, J' multisets of size 3 in {1..n},
#      b1[J] = sum_{pi in S3} sgn(pi) x(pi1,J1) x(pi2,J2) x(pi3,J3)  (= det(V_sigma1) (x) Sym^3 W).
#   Separately (part 1) we check numerically that span{ f^* Omega : f = (alpha_1..alpha_n), alpha in L^n }
#   (Omega = x1 x2 x3 y1 y2 y3, the tau-component of the Weil class of A) equals span{b1[J] b2[J']}.
# Part 2: R_{2k} = span(w R_{2k-2} + U R_{2k-6}) computed mod p; compare dim R_{2k} with dim B^k(A^n)
#   from the character computation (hodge_dims.py) and dim C[w]_{2k} with dim D^k(A^n).
import sys, itertools, random, math, json
import numpy as np
from hodge_dims import table

P = 2147483647

def popcount(x): return bin(x).count('1')

def mono_mul(m1, m2):
    if m1 & m2:
        return 0, 0
    s = 0
    mm = m2
    while mm:
        j = (mm & -mm).bit_length() - 1
        s += popcount(m1 >> (j + 1))
        mm &= mm - 1
    return (m1 | m2), (-1 if s & 1 else 1)

def el_mul(A, B):
    R = {}
    for m1, c1 in A.items():
        for m2, c2 in B.items():
            m, sg = mono_mul(m1, m2)
            if sg:
                R[m] = (R.get(m, 0) + sg * c1 * c2) % P
    return {k: v for k, v in R.items() if v}

def el_add(A, B, cb=1):
    R = dict(A)
    for k, v in B.items():
        R[k] = (R.get(k, 0) + cb * v) % P
    return {k: v for k, v in R.items() if v}

class Model:
    def __init__(self, n):
        self.n = n
        self.idx = {}
        c = 0
        for blk in ['x', 'xb', 'y', 'yb']:
            for a in range(3):
                for j in range(n):
                    self.idx[(blk, a, j)] = c; c += 1
    def var(self, blk, a, j): return {1 << self.idx[(blk, a, j)]: 1}
    def omega(self, b1, b2, j, k):
        E = {}
        for a in range(3):
            E = el_add(E, el_mul(self.var(b1, a, j), self.var(b2, a, k)))
        return E
    def beta(self, blk, J):
        E = {}
        for perm in itertools.permutations(range(3)):
            sg = 1
            for i in range(3):
                for k in range(i + 1, 3):
                    if perm[i] > perm[k]: sg = -sg
            t = {0: 1}
            for i in range(3):
                t = el_mul(t, self.var(blk, perm[i], J[i]))
            E = el_add(E, t, sg)
        return E

class Echelon:
    def __init__(self): self.rows = {}           # pivot -> row (dict), pivot = max key, row normalised
    def reduce(self, v):
        v = dict(v)
        while v:
            p = max(v)
            if p not in self.rows:
                return v, p
            r = self.rows[p]; c = v[p]
            for k, val in r.items():
                v[k] = (v.get(k, 0) - c * val) % P
                if v[k] == 0: del v[k]
        return v, None
    def add(self, v):
        v, p = self.reduce(v)
        if not v:
            return False
        inv = pow(v[p], P - 2, P)
        self.rows[p] = {k: (val * inv) % P for k, val in v.items()}
        return True
    def basis(self): return list(self.rows.values())

def part1_pullback_span(n, trials=60, seed=3):
    """numeric: rank of { (s1(alpha)^{(x)3}) (x) (s2(alpha)^{(x)3}) in Sym^3 C^n (x) Sym^3 C^n }."""
    rng = np.random.default_rng(seed)
    d, m = 7, 5
    sd, sm = math.sqrt(d), math.sqrt(m)
    mons = [J for J in itertools.combinations_with_replacement(range(n), 3)]
    rows = []
    for _ in range(trials):
        al = rng.integers(-4, 5, size=(n, 4))          # alpha_j = a0 + a1 s + a2 w + a3 s w
        s1 = al[:, 0] + al[:, 2] * sm + 1j * sd * (al[:, 1] + al[:, 3] * sm)
        s2 = al[:, 0] - al[:, 2] * sm + 1j * sd * (al[:, 1] - al[:, 3] * sm)
        # coefficient of the monomial J in u^3 (symmetric power) = multinomial * prod u_J
        def sym3(u):
            out = []
            for J in mons:
                cnt = [J.count(i) for i in range(n)]
                mult = math.factorial(3) // np.prod([math.factorial(c) for c in cnt])
                out.append(mult * np.prod([u[i] for i in J]))
            return np.array(out)
        rows.append(np.kron(sym3(s1), sym3(s2)))
    M = np.array(rows)
    sv = np.linalg.svd(M, compute_uv=False)
    rank = int((sv > 1e-8 * sv[0]).sum())
    return rank, len(mons) ** 2

def part2_generation(n, kmax):
    M = Model(n)
    W = [M.omega('x', 'xb', j, k) for j in range(n) for k in range(n)] + \
        [M.omega('y', 'yb', j, k) for j in range(n) for k in range(n)]
    Js = list(itertools.combinations_with_replacement(range(n), 3))
    U = [el_mul(M.beta('x', J), M.beta('y', Jp)) for J in Js for Jp in Js] + \
        [el_mul(M.beta('xb', J), M.beta('yb', Jp)) for J in Js for Jp in Js]
    # sanity: U elements nonzero, independent
    E = Echelon(); rkU = sum(E.add(u) for u in U)
    Rw = {0: [{0: 1}]}; R = {0: [{0: 1}]}
    res = []
    for k in range(1, kmax + 1):
        Ew = Echelon()
        for r in Rw[k - 1]:
            for w in W:
                Ew.add(el_mul(w, r))
        Rw[k] = Ew.basis()
        Er = Echelon()
        for r in R[k - 1]:
            for w in W:
                Er.add(el_mul(w, r))
        if k >= 3:
            for r in R[k - 3]:
                for u in U:
                    Er.add(el_mul(u, r))
        R[k] = Er.basis()
        res.append((k, len(R[k]), len(Rw[k])))
        print('   n=%d k=%d  dim R_2k = %d   dim C[w]_2k = %d' % (n, k, len(R[k]), len(Rw[k])), flush=True)
    return rkU, res

if __name__ == '__main__':
    n = int(sys.argv[1]); kmax = int(sys.argv[2])
    rk, tot = part1_pullback_span(n)
    print('part 1 (n=%d): rank of pullbacks of the Weil class = %d of %d' % (n, rk, tot), flush=True)
    rkU, res = part2_generation(n, kmax)
    tab, _ = table(n)
    print('part 2 (n=%d): rank U = %d' % (n, rkU))
    ok = True
    for (k, r, rw) in res:
        B, D = tab[k][1], tab[k][2]
        flag = (r == B and rw == D)
        ok &= flag
        print('   k=%2d  generated %6d  Hodge %6d  |  C[divisors] %6d  Lefschetz %6d   %s' % (k, r, B, rw, D, 'OK' if flag else 'MISMATCH'))
    print('ALL OK' if ok else 'SOME MISMATCH')
