# make_certificate.py -- pure Python 3; writes certificate.json for Section 5 of the note (Proposition 5.1,
# Theorem 5.2, Proposition 5.3 and the simple sixfolds of Proposition 4.1).
# For every REDUCED pair (G, Phi) with d >= 1 and g <= 6 (one record per G-orbit of CM types, as in enum_g{g}.json)
# the certificate gives: the generators of G (permutations of the 2g embeddings, rho(i) = i + g mod 2g), the orbits,
# the CM type Phi, a basis of Lambda_U, and
#   - if Lambda_U is generated by Weil characters of kinds (a)-(d) of Section 5: a list of such characters (each
#     given by the imaginary quadratic field K as the values of a homomorphism G -> {+1,-1} on the generators, and
#     the multiplicities c_i, the sign of c_i choosing the embedding of K) and an integer matrix T with
#     (basis of Lambda_U) = T * (list of characters);
#   - otherwise (the 48 G-orbits of Table 2) the label "table2".
# check_certificate.py verifies the file without using any other file of the repository.
# This program uses verify_enum.py (pure Python) only to find the characters; the checker re-derives everything.
#   usage:  python make_certificate.py      (writes certificate.json)
import json, os, sys, itertools

HERE = os.path.dirname(os.path.abspath(__file__))
ENUM = os.path.dirname(HERE)
sys.path.insert(0, ENUM)
from verify_enum import group_struct, wvec, hnf, set_orbit   # noqa: E402

DMAX = 6


def kind_of(cv, sz):
    D = sum(abs(x) * s for x, s in zip(cv, sz))
    if D == 2:
        return 'a'
    if D == 4:
        return 'b'
    if D == 6 and any(x != 0 and s % 2 == 1 for x, s in zip(cv, sz)):
        return 'c'
    if D == 6 and sum(abs(x) for x in cv) == 1:
        return 'd'
    return None


def candidates(G, g, Phi):
    gs = group_struct(G, g)
    Ps = set(Phi)
    out = []
    for K, sv in zip(gs['Ks'], _signs(G, g, gs)):
        oids = sorted(K)
        b = [wvec(K[o], g) for o in oids]
        t = [2 * len(Ps & set(K[o])) - len(K[o]) for o in oids]
        sz = [len(K[o]) for o in oids]
        for cv in itertools.product(*[range(-(DMAX // s), DMAX // s + 1) for s in sz]):
            D = sum(abs(x) * s for x, s in zip(cv, sz))
            if D == 0 or D > DMAX or sum(x * y for x, y in zip(cv, t)) != 0:
                continue
            k = kind_of(cv, sz)
            if k is None:
                continue
            w = [sum(x * bb[j] for x, bb in zip(cv, b)) for j in range(g)]
            if any(w):
                out.append(dict(chi=list(sv), c={str(o): x for o, x in zip(oids, cv) if x}, kind=k, D=D, w=w))
    return out


def _signs(G, g, gs):
    """The sign vector (values on the generators) of each K in gs['Ks'], recomputed from its blocks."""
    res = []
    n = 2 * g
    for K in gs['Ks']:
        o = sorted(K)[0]
        B = frozenset(K[o])
        Bc = frozenset((x + g) % n for x in B)
        sv = []
        for p in G['gens']:
            im = frozenset(p[x] for x in B)
            sv.append(1 if im == B else -1 if im == Bc else 0)
        assert 0 not in sv
        res.append(tuple(sv))
    return res


def express(LU, W):
    """Integer matrix T with LU = T * W (rows), by integer row reduction of W with a transformation matrix."""
    m = len(W)
    rows = [(list(w), [1 if k == i else 0 for k in range(m)]) for i, w in enumerate(W)]
    g = len(W[0])
    basis = []                       # echelon rows (vector, combination)
    col = 0
    work = rows
    while work and col < g:
        nz = [r for r in work if r[0][col] != 0]
        z = [r for r in work if r[0][col] == 0]
        while len(nz) > 1:
            nz.sort(key=lambda r: abs(r[0][col]))
            p = nz[0]
            new = [p]
            for r in nz[1:]:
                q = r[0][col] // p[0][col]
                v = [a - q * b for a, b in zip(r[0], p[0])]
                cmb = [a - q * b for a, b in zip(r[1], p[1])]
                (new if v[col] != 0 else z).append((v, cmb))
            nz = new
        if nz:
            basis.append(nz[0])
        work = z
        col += 1
    # solve LU[r] = sum_k a_k basis[k] (echelon, so successive elimination), then compose combinations
    T = []
    for target in LU:
        rem = list(target)
        comb = [0] * m
        for v, cmb in basis:
            c0 = next(i for i, x in enumerate(v) if x != 0)
            if rem[c0] % v[c0] != 0:
                return None
            q = rem[c0] // v[c0]
            rem = [a - q * b for a, b in zip(rem, v)]
            comb = [a + q * b for a, b in zip(comb, cmb)]
        if any(rem):
            return None
        T.append(comb)
    return T


records = []
for g in range(1, 7):
    D = json.load(open(os.path.join(ENUM, 'enum_g%d.json' % g)))
    groups = {G['gid']: G for G in D['groups']}
    for c in D['cases']:
        if not (c['reduced'] and c['d'] >= 1):
            continue
        G = groups[c['gid']]
        LU = hnf(c['LU'])
        cand = candidates(G, g, c['Phi'])
        # greedy choice of characters that enlarge the lattice, then the transformation
        chosen, cur = [], []
        for v in sorted(cand, key=lambda v: (v['D'], v['kind'])):
            if cur and hnf(cur + [v['w']]) == hnf(cur):
                continue
            chosen.append(v)
            cur.append(v['w'])
            if hnf(cur) == LU:
                break
        rec = dict(g=g, gid=c['gid'], Nclass=c['Nclass'], gens=G['gens'], orbits=[sorted(o) for o in G['orbits']],
                   Phi=sorted(c['Phi']), d=c['d'], LU=LU)
        if cur and hnf(cur) == LU:
            T = express(LU, cur)
            assert T is not None
            rec['status'] = 'kinds a-d'
            rec['weil'] = [dict(chi=v['chi'], c=v['c'], kind=v['kind']) for v in chosen]
            rec['T'] = T
        else:
            rec['status'] = 'table2'
        records.append(rec)

out = dict(description='Certificate for Section 5 of the note: reduced pairs (G, Phi) with d >= 1 and g <= 6; see '
                       'README.txt in this folder.', records=records)
with open(os.path.join(HERE, 'certificate.json'), 'w', newline='\n') as f:
    json.dump(out, f, separators=(',', ':'))
    f.write('\n')
cnt = {}
for r in records:
    cnt[(r['g'], r['status'])] = cnt.get((r['g'], r['status']), 0) + 1
print('records:', len(records), sorted(cnt.items()))
