# first_power.py -- for each reduced strict-failing case: smallest n such that A^n carries a Hodge class whose
# U_E-character lies in Lambda_U but NOT in the lattice generated by Weil characters of dimension <= 6
# (imaginary-quadratic with multiplicities = the D<=6 part; general CM fields add nothing at D<=6 here, see general_weil2).
# A character chi in Z^g (coords: rho-pairs) occurs on A^n iff max|chi_i| <= n.  (pure python)
import json, itertools, os
from verify_enum import group_struct, wvec, hnf, sat_index, rank
HERE = os.path.dirname(os.path.abspath(__file__))
for g in [5, 6]:
    D = json.load(open(os.path.join(HERE, 'enum_g%d.json' % g))); groups = {G['gid']: G for G in D['groups']}
    gw = {(r['gid'], tuple(r['Phi'])): r for r in json.load(open(os.path.join(HERE, 'general_weil2_out_D12.json')))[str(g)]}
    res = {}
    for c in D['cases']:
        if not (c['reduced'] and not c['passed']):
            continue
        gs = group_struct(groups[c['gid']], g); Ps = set(c['Phi']); W6 = []
        for K in gs['Ks']:
            o = sorted(K); b = [wvec(K[x], g) for x in o]; t = [2 * len(Ps & set(K[x])) - len(K[x]) for x in o]; sz = [len(K[x]) for x in o]
            for cv in itertools.product(*[range(-6 // s, 6 // s + 1) for s in sz]):
                if any(cv) and sum(abs(a) * s for a, s in zip(cv, sz)) <= 6 and sum(a * y for a, y in zip(cv, t)) == 0:
                    w = [sum(a * bb[j] for a, bb in zip(cv, b)) for j in range(g)]
                    if any(w): W6.append(w)
        LW = hnf(W6) if W6 else []
        LU = c['LU']; d = c['d']
        def inLU(v): return rank(LU + [v]) == d
        def inLW(v): return bool(LW) and hnf(LW + [v]) == LW
        first = None
        for n in range(1, 5):
            for v in itertools.product(range(-n, n + 1), repeat=g):
                if any(v) and max(map(abs, v)) == n and inLU(list(v)) and not inLW(list(v)):
                    first = (n, list(v)); break
            if first: break
        part = tuple(sorted((len(o) // 2 for o in groups[c['gid']]['orbits']), reverse=True))
        key = (part, c['d'], gw[(c['gid'], tuple(c['Phi']))]['Dmin'])
        res.setdefault(key, set()).add(first[0] if first else None)
        print(g, c['gid'], c['Phi'], part, 'd=%d' % d, 'genDmin', gw[(c['gid'], tuple(c['Phi']))]['Dmin'], 'first unexplained power n =', first)
    print("summary g=%d:" % g, res)
