# verify_enum.py -- INDEPENDENT VERIFIER (pure Python; no Sage/GAP).  Recomputes everything from the generators.
#   usage:  python verify_enum.py 1,2,3,4,5,6
# Own implementations: group closure (BFS), orbits (union-find), CM-type orbit (BFS on sets), ranks / integer kernel /
# Hermite normal form / saturation index (gcd of maximal minors, Bareiss determinants), 2-block systems by brute force
# over half-subsets, primitivity via minimal blocks generated by pairs, G-set isomorphisms by BFS.
import json, sys, os, itertools, time, random
from math import gcd
from functools import reduce

HERE = os.path.dirname(os.path.abspath(__file__))


# ---------------- integer linear algebra ----------------
def hnf(A):
    """Row Hermite normal form: returns nonzero rows; pivots positive, entries above pivots in [0,pivot)."""
    A = [list(r) for r in A]
    m = len(A)
    if m == 0:
        return []
    n = len(A[0])
    r = 0
    for c in range(n):
        if r == m:
            break
        while True:
            nz = [i for i in range(r, m) if A[i][c] != 0]
            if not nz:
                break
            i0 = min(nz, key=lambda i: abs(A[i][c]))
            A[r], A[i0] = A[i0], A[r]
            clean = True
            for i in range(r + 1, m):
                if A[i][c] != 0:
                    q = A[i][c] // A[r][c]
                    A[i] = [a - q * b for a, b in zip(A[i], A[r])]
                    if A[i][c] != 0:
                        clean = False
            if clean:
                break
        if A[r][c] != 0:
            if A[r][c] < 0:
                A[r] = [-a for a in A[r]]
            for i in range(r):
                q = A[i][c] // A[r][c]
                if q:
                    A[i] = [a - q * b for a, b in zip(A[i], A[r])]
            r += 1
    return [row for row in A[:r] if any(row)]


def rank(A):
    return len(hnf(A)) if A else 0


def int_kernel(M, ncols):
    """Z-basis (HNF) of {x in Z^ncols : M x = 0}."""
    k = len(M)
    aug = [[M[i][j] for i in range(k)] + [1 if t == j else 0 for t in range(ncols)] for j in range(ncols)]
    # reduce on first k columns only (unimodular row ops)
    A = aug
    m = len(A)
    r = 0
    for c in range(k):
        if r == m:
            break
        while True:
            nz = [i for i in range(r, m) if A[i][c] != 0]
            if not nz:
                break
            i0 = min(nz, key=lambda i: abs(A[i][c]))
            A[r], A[i0] = A[i0], A[r]
            clean = True
            for i in range(r + 1, m):
                if A[i][c] != 0:
                    q = A[i][c] // A[r][c]
                    A[i] = [a - q * b for a, b in zip(A[i], A[r])]
                    if A[i][c] != 0:
                        clean = False
            if clean:
                break
        if A[r][c] != 0:
            r += 1
    ker = [row[k:] for row in A[r:]]
    for row in A[r:]:
        assert not any(row[:k])
    return hnf(ker)


def det_bareiss(Mx):
    M = [list(r) for r in Mx]
    n = len(M)
    if n == 0:
        return 1
    sign, prev = 1, 1
    for k in range(n - 1):
        if M[k][k] == 0:
            sw = next((i for i in range(k + 1, n) if M[i][k] != 0), None)
            if sw is None:
                return 0
            M[k], M[sw] = M[sw], M[k]
            sign = -sign
        for i in range(k + 1, n):
            for j in range(k + 1, n):
                M[i][j] = (M[i][j] * M[k][k] - M[i][k] * M[k][j]) // prev
        prev = M[k][k]
    return sign * M[n - 1][n - 1]


def sat_index(B):
    """[saturation : lattice] for a basis B (rows, full row rank) = gcd of maximal minors."""
    r = len(B)
    if r == 0:
        return 1
    n = len(B[0])
    gg = 0
    for cols in itertools.combinations(range(n), r):
        gg = gcd(gg, det_bareiss([[row[c] for c in cols] for row in B]))
        if gg == 1:
            return 1
    return abs(gg)


# ---------------- permutation group helpers ----------------
def closure_order(gens, n):
    e = tuple(range(n))
    seen = {e}
    fr = [e]
    while fr:
        nf = []
        for x in fr:
            for p in gens:
                y = tuple(p[x[i]] for i in range(n))
                if y not in seen:
                    seen.add(y)
                    nf.append(y)
        fr = nf
    return len(seen)


def orbits_uf(gens, n):
    par = list(range(n))
    def f(x):
        while par[x] != x:
            par[x] = par[par[x]]
            x = par[x]
        return x
    for p in gens:
        for i in range(n):
            a, b = f(i), f(p[i])
            if a != b:
                par[a] = b
    d = {}
    for i in range(n):
        d.setdefault(f(i), []).append(i)
    return sorted((sorted(v) for v in d.values()), key=min)


def set_orbit(gens, S):
    S = frozenset(S)
    seen = {S}
    fr = [S]
    while fr:
        nf = []
        for T in fr:
            for p in gens:
                U = frozenset(p[x] for x in T)
                if U not in seen:
                    seen.add(U)
                    nf.append(U)
        fr = nf
    return seen


def min_block(gens, O, a, b):
    """partition of O generated by identifying a and b (finest G-invariant partition with a~b)."""
    par = {x: x for x in O}
    def f(x):
        while par[x] != x:
            par[x] = par[par[x]]
            x = par[x]
        return x
    def union(x, y):
        x, y = f(x), f(y)
        if x != y:
            par[x] = y
            return True
        return False
    union(a, b)
    changed = True
    while changed:
        changed = False
        for p in gens:
            for x in O:
                for y in O:
                    pass
        # efficient: for each class, images of class members under p must be in one class
        classes = {}
        for x in O:
            classes.setdefault(f(x), []).append(x)
        for p in gens:
            for cl in classes.values():
                imgs = [p[x] for x in cl]
                for z in imgs[1:]:
                    if union(imgs[0], z):
                        changed = True
    classes = {}
    for x in O:
        classes.setdefault(f(x), []).append(x)
    return sorted(tuple(sorted(c)) for c in classes.values())


def gset_isos(gens, Oa, Ob):
    """all G-set isomorphisms Oa -> Ob (as dicts), by BFS from a base point."""
    a0 = Oa[0]
    res = []
    for b0 in Ob:
        f = {a0: b0}
        st = [a0]
        ok = True
        while st and ok:
            x = st.pop()
            for p in gens:
                y, fy = p[x], p[f[x]]
                if y in f:
                    if f[y] != fy:
                        ok = False
                        break
                else:
                    f[y] = fy
                    st.append(y)
        if ok and len(f) == len(Oa) and len(set(f.values())) == len(Oa):
            res.append(f)
    return res


# ---------------- verification ----------------
def group_struct(G, g):
    n = 2 * g
    gens = G['gens']
    rho = lambda x: (x + g) % n
    orbs = orbits_uf(gens, n)
    # 2-block systems swapped by rho: brute force over subsets with one point of each rho-pair in O
    Kmap = {}
    allsys = []
    for oi, O in enumerate(orbs):
        reps = [x for x in O if x < g]
        quads = []
        for bits in range(2 ** len(reps)):
            B = frozenset(x if not (bits >> i) & 1 else rho(x) for i, x in enumerate(reps))
            if min(O) not in B:
                continue
            Bc = frozenset(rho(x) for x in B)
            sv = []
            ok = True
            for p in gens:
                im = frozenset(p[x] for x in B)
                if im == B:
                    sv.append(1)
                elif im == Bc:
                    sv.append(-1)
                else:
                    ok = False
                    break
            if ok:
                quads.append((tuple(sv), sorted(B)))
        for sv, B in quads:
            Kmap.setdefault(sv, {})
            assert oi not in Kmap[sv]
            Kmap[sv][oi] = B
        # minimal nontrivial block systems (generated by pairs)
        sy = set()
        for a, b in itertools.combinations(O, 2):
            part = min_block(gens, O, a, b)
            if 1 < len(part[0]) < len(O):
                sy.add(tuple(part))
        allsys.append(sorted(sy))
    Ks = [Kmap[sv] for sv in sorted(Kmap)]
    isos = {}
    for i, j in itertools.combinations(range(len(orbs)), 2):
        if len(orbs[i]) == len(orbs[j]):
            fl = gset_isos(gens, orbs[i], orbs[j])
            if fl:
                isos[(i, j)] = fl
    return dict(orbs=orbs, Ks=Ks, sys=allsys, isos=isos)


def wvec(B, g):
    w = [0] * g
    for x in B:
        if x < g:
            w[x] += 1
        else:
            w[x - g] -= 1
    return w


def verify_case(c, G, gs, g, check_mult=True):
    n = 2 * g
    gens = G['gens']
    Phi = c['Phi']
    Ps = set(Phi)
    errs = []
    orb = set_orbit(gens, Phi)
    if len(orb) != c['norb']:
        errs.append('norb')
    if min(tuple(sorted(T)) for T in orb) != tuple(Phi):
        errs.append('Phi not orbit min')
    otypes = [sorted(T) for T in orb]
    S = [[1 if j in T else 0 for j in range(n)] for T in otypes]
    mu = [[1 if i in T else -1 for i in range(g)] for T in otypes]
    rS, rmu = rank(S), rank(mu)
    if rS != c['dimMT'] or rS != rmu + 1:
        errs.append('dimMT')
    d = g - rmu
    if d != c['d']:
        errs.append('d')
    LU = int_kernel(mu, g)
    if len(LU) != d:
        errs.append('LU rank')
    if hnf(c['LU']) != LU:
        errs.append('LU lattice')
    if sat_index(LU) != 1:
        errs.append('LU not saturated')
    # admissible Weil characters (strict)
    adm = set()
    ws = []
    for K in gs['Ks']:
        oids = sorted(K)
        for r in range(1, len(oids) + 1):
            for J in itertools.combinations(oids, r):
                for ch in itertools.product([0, 1], repeat=r):
                    B = []
                    for e, o in zip(ch, J):
                        B += K[o] if e == 0 else [(x + g) % n for x in K[o]]
                    if 2 * len(Ps & set(B)) != len(B):
                        continue
                    XJ = min(x for o in J for x in gs['orbs'][o])
                    if XJ in B:
                        adm.add(tuple(sorted(B)))
                    w = wvec(B, g)
                    if any(sum(a * b for a, b in zip(w, m)) for m in mu):
                        errs.append('adm not orth')
                    ws.append(w)
    if adm != set(tuple(a['B']) for a in c['adm']):
        errs.append('adm set')
    LW = hnf(ws) if ws else []
    rW = len(LW)
    if rW != c['rankW']:
        errs.append('rankW')
    idx = sat_index(LW) if rW == d else None
    if (c['index'] if c['index'] is not None else None) != idx and not (d == 0 and c['index'] == 1):
        errs.append('index %s vs %s' % (c['index'], idx))
    passed = (rW == d and (d == 0 or idx == 1))
    if passed != c['passed']:
        errs.append('passed')
    # primitivity / isogeny / reduced
    prim = []
    for oi, O in enumerate(gs['orbs']):
        Pi = Ps & set(O)
        imp = any(all(set(b) <= Pi or not (set(b) & Pi) for b in part) for part in gs['sys'][oi])
        prim.append(not imp)
    if prim != c['primitive']:
        errs.append('primitive')
    isog = []
    for (i, j), fl in gs['isos'].items():
        Pi = Ps & set(gs['orbs'][i])
        Pj = Ps & set(gs['orbs'][j])
        if any(set(f[x] for x in Pi) == Pj for f in fl):
            isog.append([i, j])
    if sorted(isog) != sorted(c['isog']):
        errs.append('isog')
    red = all(prim) and not isog
    if red != c['reduced']:
        errs.append('reduced')
    # multiplicity extension
    if check_mult and 'mult' in c:
        Dmax = c['mult']['Dmax']
        vecs = []
        for K in gs['Ks']:
            oids = sorted(K)
            b = [wvec(K[o], g) for o in oids]
            t = [2 * len(Ps & set(K[o])) - len(K[o]) for o in oids]
            sz = [len(K[o]) for o in oids]
            ranges = [range(-(Dmax // s), Dmax // s + 1) for s in sz]
            for cv in itertools.product(*ranges):
                D = sum(abs(x) * s for x, s in zip(cv, sz))
                if D == 0 or D > Dmax or sum(x * y for x, y in zip(cv, t)) != 0:
                    continue
                w = [sum(x * bb[j] for x, bb in zip(cv, b)) for j in range(g)]
                if any(w):
                    vecs.append((D, w))
        qrank = rank([w for D, w in vecs]) if vecs else 0
        Dmin = 0 if d == 0 else None
        if d > 0:
            for D in sorted(set(v[0] for v in vecs)):
                L = hnf([w for DD, w in vecs if DD <= D])
                if len(L) == d and sat_index(L) == 1:
                    Dmin = D
                    break
        if Dmin != c['mult']['Dmin'] or qrank != c['mult']['qrank']:
            errs.append('mult %s/%s vs %s/%s' % (Dmin, qrank, c['mult']['Dmin'], c['mult']['qrank']))
    return errs


if __name__ == '__main__':
    gl = list(map(int, sys.argv[1].split(',')))
    out = open(os.path.join(HERE, 'verify_out.txt'), 'a')
    def P(*a):
        print(*a); print(*a, file=out); out.flush()
    for g in gl:
        t0 = time.time()
        D = json.load(open(os.path.join(HERE, 'enum_g%d.json' % g)))
        n = 2 * g
        groups = {G['gid']: G for G in D['groups']}
        gerr = 0
        gsd = {}
        for gid, G in groups.items():
            if closure_order(G['gens'], n) != G['order']:
                gerr += 1
            rho = [(i + g) % n for i in range(n)]
            # rho in G and centralizes generators
            for p in G['gens']:
                if any(p[rho[i]] != rho[p[i]] for i in range(n)):
                    gerr += 1
            gs = group_struct(G, g)
            if gs['orbs'] != G['orbits']:
                gerr += 1
            gsd[gid] = gs
        nbad = 0
        stats = dict(cases=0, d_ge1=0, reduced=0, red_fail=0, mult_checked=0)
        bad = []
        for c in D['cases']:
            errs = verify_case(c, groups[c['gid']], gsd[c['gid']], g)
            stats['cases'] += 1
            stats['d_ge1'] += c['d'] >= 1
            stats['reduced'] += c['reduced']
            stats['red_fail'] += c['reduced'] and not c['passed']
            stats['mult_checked'] += 'mult' in c
            if errs:
                nbad += 1
                bad.append((c['gid'], c['Phi'], errs))
        # completeness: per group, the stored Phi's are representatives of ALL G-orbits on the 2^g CM types, each once
        byg = {}
        for c in D['cases']:
            byg.setdefault(c['gid'], []).append(c['Phi'])
        alltypes = set(frozenset(i + g * ((m >> i) & 1) for i in range(g)) for m in range(2 ** g))
        cerr = 0
        for gid, G in groups.items():
            cov = []
            for Phi in byg.get(gid, []):
                cov += list(set_orbit(G['gens'], Phi))
            if len(cov) != len(set(cov)) or set(cov) != alltypes:
                cerr += 1
        P("g=%d: groups %d (group-level errors: %d ; type-orbit completeness errors: %d) ; cases verified %d ; disagreements %d ; stats %s ; %.1fs" %
          (g, len(groups), gerr, cerr, stats['cases'], nbad, stats, time.time() - t0))
        for b in bad[:20]:
            P("   DISAGREE", b)
