# hodge_ring.sage -- Hodge classes on A^k for a type III sixfold (Hg_C = SO(W), W = C^6),
# H^*(A^k)_C = /\^*(W (x) U'), U' = C^{2k} (U' = U (x) C^k, D (x) C = End(U)).
# For each GL(U')-weight mu (dominant) and degree d:
#   inv(mu)  = dim of SO(W)-invariants in the weight-mu part  (kernel of so(6) simple root vectors
#              on the SO-weight-0 subspace),
#   gen(mu)  = dim of the span of products of degree-2 invariants theta_{st} (divisor classes) and
#              degree-6 "determinant" classes Omega_nu (coefficients of det_W (x) u^6, u in U').
# Claim tested: inv(mu) == gen(mu) for all mu (=> Hodge ring of A^k generated by divisors + Omega's).
# Also records dim of the O(W)-invariant part (generated by thetas only) to show Omega's are needed.
# Usage: sage hodge_ring.sage [P [KMAX [DMAX]]]  (defaults 1000003 2 12); runs k = 1..KMAX, d = 0..DMAX
# and writes the log hodge_ring_p{P}_k{KMAX}_d{DMAX}.txt next to this script.
import itertools, sys, time, os
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))

P = int(sys.argv[1]) if len(sys.argv) > 1 else 1000003
KMAX = int(sys.argv[2]) if len(sys.argv) > 2 else 2
DMAX = int(sys.argv[3]) if len(sys.argv) > 3 else 12
Fp = GF(P)

# W basis: 0,1,2 = e1,e2,e3 ; 3,4,5 = f1,f2,f3 ; <e_i,f_i> = 1
def root_ops():
    ops = []
    def Eminus(i, j):   # E_{eps_i - eps_j}: e_j -> e_i, f_i -> -f_j
        return {j: [(i, 1)], 3+i: [(3+j, -1)]}
    def Eplus(i, j):    # E_{eps_i + eps_j}: f_j -> e_i, f_i -> -e_j
        return {3+j: [(i, 1)], 3+i: [(j, -1)]}
    def Fplus(i, j):    # E_{-eps_i - eps_j}: e_j -> f_i, e_i -> -f_j
        return {j: [(3+i, 1)], i: [(3+j, -1)]}
    # simple roots of D3: e1-e2, e2-e3, e2+e3 and their negatives
    ops = [Eminus(0, 1), Eminus(1, 2), Eplus(1, 2), Eminus(1, 0), Eminus(2, 1), Fplus(1, 2)]
    return ops
OPS = root_ops()

def canon(lst):
    """lst: list of (s,w) basis vectors; return (sign, sorted tuple) or (0,None) if repeated."""
    if len(set(lst)) < len(lst): return 0, None
    # sign of sorting permutation
    arr = list(lst); sign = 1
    # insertion sort counting swaps
    for a in range(1, len(arr)):
        b = a
        while b > 0 and arr[b-1] > arr[b]:
            arr[b-1], arr[b] = arr[b], arr[b-1]; sign = -sign; b -= 1
    return sign, tuple(arr)

def basis_mu(mu):
    cols = []
    for s, m in enumerate(mu):
        cols.append([S for S in itertools.combinations(range(6), m)])
    out = []
    for choice in itertools.product(*cols):
        wt = [0, 0, 0]
        for S in choice:
            for w in S:
                if w < 3: wt[w] += 1
                else: wt[w-3] -= 1
        if wt == [0, 0, 0]:
            out.append(tuple((s, w) for s, S in enumerate(choice) for w in S))
    return out

def inv_dim(mu):
    B = basis_mu(mu)
    if not B: return 0, 0
    rows = {}
    entries = defaultdict(int)
    for col, mono in enumerate(B):
        for oi, X in enumerate(OPS):
            for pos, (s, w) in enumerate(mono):
                if w in X:
                    for (w2, cf) in X[w]:
                        lst = list(mono); lst[pos] = (s, w2)
                        sg, key = canon(lst)
                        if sg == 0: continue
                        r = rows.setdefault((oi, key), len(rows))
                        entries[(r, col)] += sg*cf
    if not rows: return len(B), len(B)
    M = matrix(Fp, len(rows), len(B), {k: v for k, v in entries.items() if v % P != 0}, sparse=True)
    return len(B), len(B) - M.rank()

def wedge(x, y):
    out = defaultdict(int)
    for m1, c1 in x.items():
        for m2, c2 in y.items():
            sg, key = canon(list(m1) + list(m2))
            if sg: out[key] += sg*c1*c2
    return {k: v for k, v in out.items() if v != 0}

def theta(s, t):
    out = defaultdict(int)
    for i in range(3):
        for (a, b) in ((i, 3+i), (3+i, i)):
            sg, key = canon([(s, a), (t, b)])
            if sg: out[key] += sg
    return dict(out)

def omega(nu):
    # coefficient of x^nu in (w_0(x)u)^...^(w_5(x)u), u = sum x_s u_s
    out = defaultdict(int)
    slots = [s for s, m in enumerate(nu) for _ in range(m)]
    for perm in set(itertools.permutations(slots)):
        sg, key = canon([(perm[w], w) for w in range(6)])
        if sg: out[key] += sg
    return {k: v for k, v in out.items() if v != 0}

def weight_vectors(n, d):
    for c in itertools.product(range(min(d, 6)+1), repeat=n):
        if sum(c) == d: yield c

def gen_dim(mu, n, use_omega=True):
    d = sum(mu)
    pairs = [(s, t) for s in range(n) for t in range(s+1, n)]
    TH = {pt: theta(*pt) for pt in pairs}
    vecs = []
    # multisets of thetas with total weight w, times optional Omega_nu (one or two)
    def theta_products(target):
        # all multisets of pairs whose weight = target
        res = []
        def rec(idx, rem, chosen):
            if all(r == 0 for r in rem): res.append(list(chosen)); return
            if idx == len(pairs): return
            s, t = pairs[idx]
            # choose multiplicity
            mmax = min(rem[s], rem[t])
            for m in range(mmax, -1, -1):
                r2 = list(rem); r2[s] -= m; r2[t] -= m
                rec(idx+1, r2, chosen + [(s, t)]*m)
        rec(0, list(target), [])
        return res
    omegas = [None]
    if use_omega:
        if d >= 6: omegas += [(nu,) for nu in weight_vectors(n, 6)]
        if d >= 12: omegas += [(nu1, nu2) for nu1 in weight_vectors(n, 6) for nu2 in weight_vectors(n, 6) if nu1 <= nu2]
    for om in omegas:
        rest = list(mu)
        if om is not None:
            for nu in om:
                rest = [r - v for r, v in zip(rest, nu)]
        if any(r < 0 for r in rest) or sum(rest) % 2: continue
        for tp in theta_products(rest):
            v = {(): 1}
            if om is not None:
                for nu in om: v = wedge(v, omega(nu))
            for pt in tp:
                v = wedge(v, TH[pt])
                if not v: break
            if v: vecs.append(v)
    if not vecs: return 0
    keys = {}
    ent = {}
    for i, v in enumerate(vecs):
        for k, c in v.items():
            j = keys.setdefault(k, len(keys))
            if c % P: ent[(i, j)] = c
    M = matrix(Fp, len(vecs), len(keys), ent, sparse=True)
    return M.rank()

log = open(os.path.join(HERE, f'hodge_ring_p{P}_k{KMAX}_d{DMAX}.txt'), 'w')
def say(*a):
    s = ' '.join(str(x) for x in a); print(s); log.write(s + '\n'); log.flush()

say(f'prime {P}')
for k in range(1, KMAX+1):
    n = 2*k
    for d in range(0, DMAX+1, 2):
        mus = [p for p in Partitions(d, max_length=n, max_part=6)]
        tot_inv = tot_gen = tot_O = 0
        t0 = time.time()
        for p in mus:
            mu = tuple(list(p) + [0]*(n - len(p)))
            nb, iv = inv_dim(mu)
            gv = gen_dim(mu, n) if iv else 0
            go = gen_dim(mu, n, use_omega=False) if iv else 0
            flag = '' if iv == gv else '  <-- MISMATCH'
            say(f'k={k} d={d} mu={mu} zero-wt-basis={nb} inv={iv} gen(div+Omega)={gv} gen(div only)={go}{flag}')
            tot_inv += iv; tot_gen += gv; tot_O += go
        say(f'== k={k} d={d}: dominant-weight totals inv={tot_inv} gen={tot_gen} divisor-only={tot_O}  ({time.time()-t0:.1f}s)')
log.close()
